# -*- coding: utf-8 -*-
"""tensor manipulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NCCrFPtCJdQ6kV4ImQNm5u_TpRBdrNcW
"""

import tensorflow as tf
import numpy as np

with tf.Session() as sess:
  x=tf.expand_dims([0,1,2],1).eval()
  print(x)
  
for x,y,z in zip([1,2,3,4],[4,5,6,7],[7,8,9,10,11]):
  print(x,y,z)

